version: "3.8"

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: app-db
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d app_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-cache:
    image: redis:7-alpine
    container_name: app-cache
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq-mq:
    image: rabbitmq:3-management
    container_name: app-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: .
    container_name: app-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - redis-cache
      - rabbitmq-mq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/app_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_REDIS_HOST: redis-cache
      SPRING_RABBITMQ_HOST: rabbitmq-mq

volumes:
  postgres-data:
